environments:
  local:
    kubeContext: minikube
  dev:
    kubeContext: workload

---

repositories:
  - name: rustfs
    url: https://charts.rustfs.com

releases:
  - name: s3-store
    namespace: mex
    createNamespace: false
    chart: ./charts/s3-store
    missingFileHandler: Warn
    values:
      - envs/{{ .Environment.Name }}/s3-store/values.yaml
    secrets:
      - envs/{{ .Environment.Name }}/s3-store/secrets.yaml
  - name: mex-drop
    namespace: mex
    createNamespace: false
    chart: ./charts/mex-drop
    missingFileHandler: Warn
    values:
      - envs/{{ .Environment.Name }}/mex-drop/values.yaml
