minio:
  defaultBuckets: "mex-etl-dev, mex-etl-local"

  persistence:
    enabled: false
    storageClass: "nfs-client"
    accessModes:
      - ReadWriteOnce
    size: "512Mi"

  service:
    type: ClusterIP
    port: 9000 # S3 Api port
    consolePort: 9090 # Web UI port

  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: api-mex-s3.dev.platform.rki.local
        paths:
        - path: /
          pathType: Prefix

  consoleIngress:
    enabled: true
    className: "nginx"
    hosts:
      - host: console-mex-s3.dev.platform.rki.local
        paths:
        - path: /
          pathType: Prefix

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
