{{- if .Values.configMapData }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  {{- range $key, $value := .Values.configMapData }}
  {{ $key }}: {{ $value | toJson }}
  {{- end }}
{{- end }}
