apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["drop-frontend"]
          ports:
            - containerPort: 8020
          {{- if .Values.configMapData }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          {{- end }}
          {{- if .Values.frontend.env }}
          env:
            {{- range $key, $value := .Values.frontend.env }}
            - name: {{ $key }}
              value: {{ $value | toJson }}
            {{- end }}
          {{- end }}

        - name: {{ .Release.Name }}-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["drop-api"]
          ports:
            - containerPort: 8021
          {{- if .Values.configMapData }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          {{- end }}
          {{- if .Values.api.env }}
          env:
            {{- range $key, $value := .Values.api.env }}
            - name: {{ $key }}
              value: {{ $value | toJson }}
            {{- end }}
          {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: {{ .Release.Name }}-storage
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}

      {{- if .Values.persistence.enabled }}
      volumes:
        - name: {{ .Release.Name }}-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
      {{- end }}
