apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: 8020
      protocol: TCP
      name: http
    - port: {{ .Values.service.api.port }}
      targetPort: 8021
      protocol: TCP
      name: api
  selector:
    app: {{ .Release.Name }}
