rustfs:
  replicaCount: 1
  mode:
    distributed:
      enabled: false
    standalone:
      enabled: true

  secret:
    rustfs:
      access_key: "..."
      secret_key: "..."

  storageclass:
    name: "standard"
    dataStorageSize: "512Mi"

  service:
    type: ClusterIP
    endpoint:
      port: 9000
    console:
      port: 9090

  config:
    rustfs:
      address: ":9000"
      console_enable: true
      console_address: ":9090"

  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: api-s3.mex
        paths:
          - path: /
            pathType: Prefix
            servicePort: endpoint
      - host: console-s3.mex
        paths:
          - path: /
            pathType: Prefix
            servicePort: console

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
