persistence:
  storageClass: standard
  size: 1Gi

ingress:
  enabled: true
  host: drop.mex

# frontend:
#   path: "/drop"
#   env:
#     REFLEX_DEPLOY_URL: http://drop.mex/
#     REFLEX_FRONTEND_PATH: "/drop"
#     MEX_DROP_API_PORT: "80"

# api:
#   path: "/api"
#   env:
#     REFLEX_API_URL: "http://drop.mex/api"
